/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: NodeStatusReport.h
  Source: NodeStatusReport.idl
  Cyclone DDS: V0.8.2

*****************************************************************/
#ifndef DDSC_NODESTATUSREPORT_H
#define DDSC_NODESTATUSREPORT_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct NodeStatusReport
{
  char * node_name;
  uint32_t cpu_a_usage;
  uint32_t cpu_m_usage;
  uint32_t ddr_usage;
  uint32_t total_ddr;
  uint64_t timestamp;
} NodeStatusReport;

extern const dds_topic_descriptor_t NodeStatusReport_desc;

#define NodeStatusReport__alloc() \
((NodeStatusReport*) dds_alloc (sizeof (NodeStatusReport)));

#define NodeStatusReport_free(d,o) \
dds_sample_free ((d), &NodeStatusReport_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_NODESTATUSREPORT_H */
