/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: NodeStatusReport.c
  Source: NodeStatusReport.idl
  Cyclone DDS: V0.8.2

*****************************************************************/
#include "NodeStatusReport.h"

static const uint32_t NodeStatusReport_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (NodeStatusReport, node_name),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (NodeStatusReport, cpu_a_usage),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (NodeStatusReport, cpu_m_usage),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (NodeStatusReport, ddr_usage),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (NodeStatusReport, total_ddr),
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (NodeStatusReport, timestamp),
  DDS_OP_RTS
};

const dds_topic_descriptor_t NodeStatusReport_desc =
{
  sizeof (NodeStatusReport),
  8u,
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "NodeStatusReport",
  NULL,
  7,
  NodeStatusReport_ops,
  ""
};
